// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/[image].ts";
import * as $1 from "./routes/api/list.ts";
import * as $2 from "./routes/api/search.ts";
import * as $3 from "./routes/api/tags/count.ts";
import * as $4 from "./routes/api/tags/get.ts";
import * as $5 from "./routes/api/tags/set/[hash].ts";
import * as $6 from "./routes/api/upload.ts";
import * as $7 from "./routes/index.tsx";
import * as $8 from "./routes/upload.tsx";
import * as $$0 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/api/[image].ts": $0,
    "./routes/api/list.ts": $1,
    "./routes/api/search.ts": $2,
    "./routes/api/tags/count.ts": $3,
    "./routes/api/tags/get.ts": $4,
    "./routes/api/tags/set/[hash].ts": $5,
    "./routes/api/upload.ts": $6,
    "./routes/index.tsx": $7,
    "./routes/upload.tsx": $8,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
